python run_riddle-generation.py \
    --model_name_or_path fnlp/bart-base-chinese \
    --do_train \
    --source_lang en \
    --target_lang ro \
    --train_file data/all/train.json \
    --num_train_epochs 8 \
    --learning_rate 5e-5 \
    --per_device_train_batch_size 8 \
    --max_source_length 64 \
    --predict_with_generate \
    --generation_max_length 15 \
    --save_steps 2000 \
    --output_dir fnlp-base-all \
    --overwrite_output_dir